version: '3.7'

services:
  email-sender:
    container_name: api-email-sender
    restart: always
    build:
      context: .
      dockerfile: src/GestioneSagre.Email.Sender/Dockerfile
    networks:
      - lan-network

networks:
  lan-network:
    external:
      name: docker-net